#!/usr/local/bin/zsh --login
brew update
brew upgrade
brew cleanup -s

gem update
gem update --system

expect -c "
    set timeout -1
    spawn gem cleanup
    set done 0

    while {\$done == 0} {
        expect {
            \"Continue with Uninstall\\\\\\? \\\\\\[Yn\\\\\\]\" { send \"n\r\" }
            \"Clean Up Complete\" { set done 1 }
        }
    }
    wait
    close $spawn_id
"

npm -g update
npm cache clean

#pip list --outdated | grep -Ev 'You are|Could not' | cut -d ' ' -f 1 | xargs -0 pip install --upgrade

rvm get latest
rvm cleanup all

heroku update

meteor update

vagrant plugin update vagrant-vmware-fusion
