#! /bin/bash

brew update
brew upgrade
brew cleanup -s

gem update
gem update --system

expect -c "
    spawn gem cleanup
    set done 0

    while {\$done == 0} {
        expect {
            \"Continue with Uninstall\\\\\\? \\\\\\[Yn\\\\\\]\" { send \"n\r\" }
            \"Clean Up Complete\" { set done 1 }
        }
    }
    wait
    close $spawn_id
"

npm -g update
npm cache clean

#pip freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs pip install -U

cabal update

rvm get latest
rvm cleanup all
