#!/usr/local/bin/zsh

alias cat=bat
alias ps=procs
alias xargs=rargs
alias ls=exa
alias find=fd
alias sed=sd
alias uniq=runiq
alias du=dust
alias cp=xcp
alias hexdump=hx
alias ascii=chars
alias tree=tre
alias bc=eva
alias rm=rip
alias dd=bcp
alias wc=cw

