#! /bin/bash
apt-get update
apt-get dist-upgrade -y
apt-get autoremove -y

gem update

expect -c "
    set timeout -1
    spawn gem cleanup
    set done 0

    while {\$done == 0} {
        expect {
            \"Continue with Uninstall\\\\\\? \\\\\\[Yn\\\\\\]\" { send \"n\r\" }
            \"Clean Up Complete\" { set done 1 }
        }
    }
    wait
    close $spawn_id
"

npm -g update
npm cache clean

python << END
import pip
from subprocess import call
 
for dist in pip.get_installed_distributions():
  call("pip install --upgrade " + dist.project_name, shell=True)
END

rvm cleanup all
rvm get latest
